import { z } from "zod";

enum Themes {
  Light = "light",
  Dark = "dark",
}

const AppConfigSchema = z.object({
  name: z.string().default("Nodebase").describe(" The application name."),

  description: z
    .string()
    .default("Generated by create next app")
    .describe(
      "The application description, and optionally the OpenGraph and twitter descriptions.",
    ),

  siteUrl: z
    .url()
    .default("http://localhost:3000")
    .describe("The domain name of the application."),

  language: z
    .string()
    .default("en")
    .describe(
      "The HTML lang attribute is used to indicate the language of the document.",
    ),

  theme: z
    .enum(Themes)
    .default(Themes.Light)
    .describe("The color scheme for the document."),
});

export type AppConfig = z.infer<typeof AppConfigSchema>;

const appConfig: AppConfig = AppConfigSchema.parse({
  name: process.env.NEXT_PUBLIC_PRODUCT_NAME,
  description: process.env.NEXT_PUBLIC_SITE_DESCRIPTION,
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL,
  language: process.env.NEXT_PUBLIC_DEFAULT_LOCALE,
  theme: process.env.NEXT_PUBLIC_DEFAULT_THEME as Themes,
});

export default appConfig;
