enum Themes {
  Light = "light",
  Dark = "dark",
}

export const config = {
  site: {
    /**
     * The application name.
     * @type {string}
     */
    name: "Nodebase",
    /**
     * The application description, and optionally the OpenGraph and twitter descriptions.
     * @type {string}
     */
    description: "Generated by create next app",
    /**
     * The domain name of the application.
     * @type {string}
     */
    siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
    /**
     * The HTML lang attribute is used to indicate the language of the document.
     * @type {string}
     */
    language: process.env.NEXT_PUBLIC_DEFAULT_LOCALE || "en",
    /**
     * The color scheme for the document.
     * @type {Themes}
     */
    theme: Themes.Light,
  },
  auth: {
    /**
     * Relative time from now in seconds when to expire the session.
     * @type {number}
     */
    sessionMaxAge: 2592000, // 30 days
    /**
     * How often the session should be updated in seconds.
     * If set to `0`, session is updated every time.
     * @type {number}
     */
    sessionUpdateAge: 86400, // 1 day
  },
  email: {
    /**
     * The hostname or IP address to connect to.
     * @type {string}
     */
    host: process.env.MAIL_HOST || "smtp.gmail.com",
    /**
     * The port to connect to (defaults to 587 if is secure is false or 465 if true).
     * @type {number}
     */
    port: 587,
    /**
     * If true the connection will use TLS when connecting to server.
     * If false then TLS is used if server supports the STARTTLS extension.
     * @type {boolean}
     */
    secure: false,
    /**
     * The username for the user if normal login is used.
     * @type {string}
     */
    user: process.env.MAIL_USERNAME,
    /**
     * The password for the user if normal login is used.
     * @type {string}
     */
    password: process.env.MAIL_PASSWORD,
    /**
     * The email address of the sender. All email addresses can be plain or formatted.
     * @type {string}
     */
    sender: process.env.MAIL_FROM_ADDRESS,
  },
};
